// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Note: this Prisma version's config datasource type only accepts `url`,
  // not `directUrl`. For migrations/db push against the pooled connection,
  // temporarily point DATABASE_URL at DIRECT_URL's value (pgbouncer can't
  // run schema changes) - see .env.example.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
